### ISSUE TITLE
导航栏的子导航栏无法点击

### ISSUE THREAD

**Issue by kaasia** [osroom/osroom#1]
demo网站的关于下的子导航栏鼠标放上就关闭了，无法点击，其他的子导航栏也有类似问题。
浏览器版本：360安全浏览器9 版本号：9.1.0.422|内核版本：55.0.2883.87

**Comment by HiWoo** [comment]
过完周末我下载个360浏览器试试，目前我只在chrome和safari里测试过

**Comment by yahuishuo** [comment]
在chrome中，子导航栏hover偶尔也会自动消失

**Comment by HiWoo** [comment]
@yahuishuo 什么版本，我在chrome没遇到这个问题
