### ISSUE TITLE
文件上传api被废弃

### ISSUE THREAD

**Issue by xujiang1** [osroom/osroom#10]
作者为什么废弃了文件上传相关的api 是要重新规划吗  我安装好了后发现文件 图片 多媒体 的的api都不能使用 显示被废弃

**Comment by HiWoo** [comment]
@xujiang1 没有废弃哦，可能是其他问题导致这个提示的，当使用了系统不存在的api的时候就会这样提示

**Comment by HiWoo** [comment]
@xujiang1 具体问题可以加QQ群556448500，注明"来自osroom-github",方便解答
