### ISSUE TITLE
部署时链接Mongo失败

### ISSUE THREAD

**Issue by MyLeoLan** [osroom/osroom#12]
[Mongodb] *Authentication failed.
Mongodb validation failure, the user name, password mistake or database configuration errors.
Tip: to open database authentication configuration

Auth Mechanism在3.0版本以后采用的是“SCRAM-SHA-1”, 之前的版本采用的是“MONGODB-CR”。

测试：我使用客户端连接，使用“SCRAM-SHA-1”方式正常链接；；使用“MONGODB-CR”失败；；估计项目中使用的就是“MONGODB-CR”。

能否修改配置文件？修改参数，感谢

**Comment by HiWoo** [comment]
@MyLeoLan 可以自行修改
