### ISSUE TITLE
Mongo开启auth授权后，如何修改pymongo的认证？

### ISSUE THREAD

**Issue by miyazawa00** [osroom/osroom#13]
在下小白，mongo未开启auth时能正常连接，但开启auth后，无法正常连接，请问需要在哪里进行修改以正常连接mongo数据库？谢谢！

**Comment by miyazawa00** [comment]
mongo开启auth验证后，mongo中各个role在各个db中登录，查询修改都没问题，在单独测试的pymongo文件中使用client.authenticate()也。但在osroom中，在apps\core\db\mongodb中，即使加dbs.authenticate()也依然报错

**Comment by HiWoo** [comment]
@miyazawa00 先贴一个错误信息我看一下吧，你检查了数据库的账号密码配置没错吧？

**Comment by HiWoo** [comment]
@miyazawa00 数据库的配置文件是osroom /apps/configs/db_config_sample.py ， 第一次使用需要把db_config_sample.py 复制一份，名称为db_config.py, 然后修改里面的数据库验证信息。部署文档里有写这一点，你试试。文档地址：[https://osroom.github.io/osroom-doc/osr/v1.0/app/install/#_5](https://osroom.github.io/osroom-doc/osr/v1.0/app/install/#_5)

**Comment by miyazawa00** [comment]
在开启auth之前是一切OK的，正常使用，并且网站其实我也架好了一段时机了，web,user和user三个库的读写都没问题，每个库,都用同一个名字的dbAdmiin权限的用户。开启auth之后，我在apps\core\db\mongodb.py里尝试在PyMongo类添加dbs.authenticate()也不行。
账号和密码我在mongo命令行中单独使用是没问题的。

下面是报错代码
 * Update and sync config.py
Traceback (most recent call last):
  File "./osroom/start.py", line 53, in <module>
    r = update_config_file(mdb_sys=mdb_sys)
  File "/root/osroom/apps/core/flask/update_config_file.py", line 27, in update_config_file
    version_info = mdb_sys.db.sys_config.find_one({"new_version":{"$exists":True}})
  File "/usr/local/lib64/python3.6/site-packages/pymongo/collection.py", line 1225, in find_one
    for result in cursor.limit(-1):
  File "/usr/local/lib64/python3.6/site-packages/pymongo/cursor.py", line 1169, in next
    if len(self.__data) or self._refresh():
  File "/usr/local/lib64/python3.6/site-packages/pymongo/cursor.py", line 1085, in _refresh
    self.__send_message(q)
  File "/usr/local/lib64/python3.6/site-packages/pymongo/cursor.py", line 975, in __send_message
    helpers._check_command_response(first)
  File "/usr/local/lib64/python3.6/site-packages/pymongo/helpers.py", line 145, in _check_command_response
    raise OperationFailure(msg % errmsg, code, response)
pymongo.errors.OperationFailure: not authorized on osr_sys to execute command { find: "sys_config", filter: { new_version: { $exists: true } }, limit: 1, singleBatch: true, lsid: { id: UUID("56a1a172-bba3-4e36-acc6-94fbee8d24cf") }, $readPreference: { mode: "secondaryPreferred" }, $db: "osr_sys" }
[root@VM_0_3_centos ~]# python3 ./osroom/start.py 
 * Check or update the database collection

感谢

**Comment by HiWoo** [comment]
@miyazawa00 你有查看你的的db_config.py配置文件吗？

**Comment by miyazawa00** [comment]
@HiWoo db_confiig里的username和password单独在mongo的shell里测试都是没问题的。
我的python版本3.6.6，mongo版本 v4.0.4-rc2，pymongo版本3.6.1

**Comment by miyazawa00** [comment]
我重新弄一遍数据库吧。重新分配一遍权限试试。好像之前因为dbAdmin没有读写权限。
