### ISSUE TITLE
我使用的是python3.7 按照文档操作到 pip install -r requirements.txt 时候报错

### ISSUE THREAD

**Issue by matianwen** [osroom/osroom#16]
ERROR: pyasn1-modules 0.2.5 has requirement pyasn1<0.5.0,>=0.4.1, but you'll have pyasn1 0.3.7 which is incompatible.
Installing collected packages: lxml, Markdown, olefile, pyasn1, PyNaCl, paramiko, Pillow, psutil, pycrypto, pycryptodome, PyJWT, pymongo, PyYAML, redis, regex, tld
  Found existing installation: lxml 4.3.3
    Uninstalling lxml-4.3.3:
      Successfully uninstalled lxml-4.3.3
  Running setup.py install for lxml ... error
    ERROR: Complete output from command /home/work/venv-osroom/bin/python3 -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-5dakyofw/lxml/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-eff9ws0c/install-record.txt --single-version-externally-managed --compile --install-headers /home/work/venv-osroom/include/site/python3.7/lxml:
    ERROR: Building lxml version 4.1.1.
    Building without Cython.
    ERROR: b'/bin/sh: xslt-config: command not found\n'
    ** make sure the development packages of libxml2 and libxslt are installed **
    
    Using build configuration of libxslt
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.7
    creating build/lib.linux-x86_64-3.7/lxml
    copying src/lxml/_elementpath.py -> build/lib.linux-x86_64-3.7/lxml
    copying src/lxml/pyclasslookup.py -> build/lib.linux-x86_64-3.7/lxml
    copying src/lxml/cssselect.py -> build/lib.linux-x86_64-3.7/lxml
    copying src/lxml/builder.py -> build/lib.linux-x86_64-3.7/lxml
    copying src/lxml/usedoctest.py -> build/lib.linux-x86_64-3.7/lxml
    copying src/lxml/ElementInclude.py -> build/lib.linux-x86_64-3.7/lxml
    copying src/lxml/sax.py -> build/lib.linux-x86_64-3.7/lxml
    copying src/lxml/doctestcompare.py -> build/lib.linux-x86_64-3.7/lxml
    copying src/lxml/__init__.py -> build/lib.linux-x86_64-3.7/lxml
    creating build/lib.linux-x86_64-3.7/lxml/includes
    copying src/lxml/includes/__init__.py -> build/lib.linux-x86_64-3.7/lxml/includes
    creating build/lib.linux-x86_64-3.7/lxml/html
    copying src/lxml/html/ElementSoup.py -> build/lib.linux-x86_64-3.7/lxml/html
    copying src/lxml/html/_setmixin.py -> build/lib.linux-x86_64-3.7/lxml/html
    copying src/lxml/html/soupparser.py -> build/lib.linux-x86_64-3.7/lxml/html
    copying src/lxml/html/diff.py -> build/lib.linux-x86_64-3.7/lxml/html
    copying src/lxml/html/builder.py -> build/lib.linux-x86_64-3.7/lxml/html
    copying src/lxml/html/usedoctest.py -> build/lib.linux-x86_64-3.7/lxml/html
    copying src/lxml/html/formfill.py -> build/lib.linux-x86_64-3.7/lxml/html
    copying src/lxml/html/clean.py -> build/lib.linux-x86_64-3.7/lxml/html
    copying src/lxml/html/_html5builder.py -> build/lib.linux-x86_64-3.7/lxml/html
    copying src/lxml/html/html5parser.py -> build/lib.linux-x86_64-3.7/lxml/html
    copying src/lxml/html/defs.py -> build/lib.linux-x86_64-3.7/lxml/html
    copying src/lxml/html/__init__.py -> build/lib.linux-x86_64-3.7/lxml/html
    copying src/lxml/html/_diffcommand.py -> build/lib.linux-x86_64-3.7/lxml/html
    creating build/lib.linux-x86_64-3.7/lxml/isoschematron
    copying src/lxml/isoschematron/__init__.py -> build/lib.linux-x86_64-3.7/lxml/isoschematron
    copying src/lxml/etree.h -> build/lib.linux-x86_64-3.7/lxml
    copying src/lxml/etree_api.h -> build/lib.linux-x86_64-3.7/lxml
    copying src/lxml/lxml.etree.h -> build/lib.linux-x86_64-3.7/lxml
    copying src/lxml/lxml.etree_api.h -> build/lib.linux-x86_64-3.7/lxml
    copying src/lxml/includes/xmlparser.pxd -> build/lib.linux-x86_64-3.7/lxml/includes
    copying src/lxml/includes/uri.pxd -> build/lib.linux-x86_64-3.7/lxml/includes
    copying src/lxml/includes/xslt.pxd -> build/lib.linux-x86_64-3.7/lxml/includes
    copying src/lxml/includes/etreepublic.pxd -> build/lib.linux-x86_64-3.7/lxml/includes
    copying src/lxml/includes/__init__.pxd -> build/lib.linux-x86_64-3.7/lxml/includes
    copying src/lxml/includes/htmlparser.pxd -> build/lib.linux-x86_64-3.7/lxml/includes
    copying src/lxml/includes/xpath.pxd -> build/lib.linux-x86_64-3.7/lxml/includes
    copying src/lxml/includes/c14n.pxd -> build/lib.linux-x86_64-3.7/lxml/includes
    copying src/lxml/includes/xmlschema.pxd -> build/lib.linux-x86_64-3.7/lxml/includes
    copying src/lxml/includes/schematron.pxd -> build/lib.linux-x86_64-3.7/lxml/includes
    copying src/lxml/includes/xmlerror.pxd -> build/lib.linux-x86_64-3.7/lxml/includes
    copying src/lxml/includes/relaxng.pxd -> build/lib.linux-x86_64-3.7/lxml/includes
    copying src/lxml/includes/dtdvalid.pxd -> build/lib.linux-x86_64-3.7/lxml/includes
    copying src/lxml/includes/xinclude.pxd -> build/lib.linux-x86_64-3.7/lxml/includes
    copying src/lxml/includes/config.pxd -> build/lib.linux-x86_64-3.7/lxml/includes
    copying src/lxml/includes/tree.pxd -> build/lib.linux-x86_64-3.7/lxml/includes
    copying src/lxml/includes/etree_defs.h -> build/lib.linux-x86_64-3.7/lxml/includes
    copying src/lxml/includes/lxml-version.h -> build/lib.linux-x86_64-3.7/lxml/includes
    creating build/lib.linux-x86_64-3.7/lxml/isoschematron/resources
    creating build/lib.linux-x86_64-3.7/lxml/isoschematron/resources/rng
    copying src/lxml/isoschematron/resources/rng/iso-schematron.rng -> build/lib.linux-x86_64-3.7/lxml/isoschematron/resources/rng
    creating build/lib.linux-x86_64-3.7/lxml/isoschematron/resources/xsl
    copying src/lxml/isoschematron/resources/xsl/XSD2Schtrn.xsl -> build/lib.linux-x86_64-3.7/lxml/isoschematron/resources/xsl
    copying src/lxml/isoschematron/resources/xsl/RNG2Schtrn.xsl -> build/lib.linux-x86_64-3.7/lxml/isoschematron/resources/xsl
    creating build/lib.linux-x86_64-3.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
    copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_schematron_message.xsl -> build/lib.linux-x86_64-3.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
    copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_abstract_expand.xsl -> build/lib.linux-x86_64-3.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
    copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_dsdl_include.xsl -> build/lib.linux-x86_64-3.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
    copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_svrl_for_xslt1.xsl -> build/lib.linux-x86_64-3.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
    copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_schematron_skeleton_for_xslt1.xsl -> build/lib.linux-x86_64-3.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
    copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/readme.txt -> build/lib.linux-x86_64-3.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
    running build_ext
    building 'lxml.etree' extension
    creating build/temp.linux-x86_64-3.7
    creating build/temp.linux-x86_64-3.7/src
    creating build/temp.linux-x86_64-3.7/src/lxml
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -DCYTHON_CLINE_IN_TRACEBACK=1 -Isrc -Isrc/lxml/includes -I/home/work/venv-osroom/include -I/usr/local/python3/include/python3.7m -c src/lxml/etree.c -o build/temp.linux-x86_64-3.7/src/lxml/etree.o -w
    In file included from src/lxml/etree.c:619:0:
    src/lxml/includes/etree_defs.h:14:31: fatal error: libxml/xmlversion.h: No such file or directory
     #include "libxml/xmlversion.h"
                                   ^
    compilation terminated.
    Compile failed: command 'gcc' failed with exit status 1
    creating tmp
    cc -I/usr/include/libxml2 -c /tmp/xmlXPathInituairntoz.c -o tmp/xmlXPathInituairntoz.o
    cc tmp/xmlXPathInituairntoz.o -lxml2 -o a.out
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
  Rolling back uninstall of lxml
  Moving to /home/work/venv-osroom/lib/python3.7/site-packages/lxml-4.3.3.dist-info/
   from /home/work/venv-osroom/lib/python3.7/site-packages/~xml-4.3.3.dist-info
  Moving to /home/work/venv-osroom/lib/python3.7/site-packages/lxml/
   from /home/work/venv-osroom/lib/python3.7/site-packages/~xml
ERROR: Command "/home/work/venv-osroom/bin/python3 -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-5dakyofw/lxml/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-eff9ws0c/install-record.txt --single-version-externally-managed --compile --install-headers /home/work/venv-osroom/include/site/python3.7/lxml" failed with error code 1 in /tmp/pip-install-5dakyofw/lxml/

**Comment by HiWoo** [comment]
@matianwen  厉害用上3.7了。我只用到3.4和3.6

**Comment by Elegant-Smile** [comment]
我用3.5也报错 @HiWoo 
ERROR: Complete output from command /home/work/osroom/bin/python3 -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-vroqxhun/psutil/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-878tn4xb/install-record.txt --single-version-externally-managed --compile --install-headers /home/work/osroom/include/site/python3.5/psutil:
    ERROR: running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.5
    creating build/lib.linux-x86_64-3.5/psutil
    copying psutil/_pslinux.py -> build/lib.linux-x86_64-3.5/psutil
    copying psutil/_pssunos.py -> build/lib.linux-x86_64-3.5/psutil
    copying psutil/_compat.py -> build/lib.linux-x86_64-3.5/psutil
    copying psutil/_psbsd.py -> build/lib.linux-x86_64-3.5/psutil
    copying psutil/_psosx.py -> build/lib.linux-x86_64-3.5/psutil
    copying psutil/_psposix.py -> build/lib.linux-x86_64-3.5/psutil
    copying psutil/_psaix.py -> build/lib.linux-x86_64-3.5/psutil
    copying psutil/_common.py -> build/lib.linux-x86_64-3.5/psutil
    copying psutil/__init__.py -> build/lib.linux-x86_64-3.5/psutil
    copying psutil/_pswindows.py -> build/lib.linux-x86_64-3.5/psutil
    creating build/lib.linux-x86_64-3.5/psutil/tests
    copying psutil/tests/test_connections.py -> build/lib.linux-x86_64-3.5/psutil/tests
    copying psutil/tests/test_bsd.py -> build/lib.linux-x86_64-3.5/psutil/tests
    copying psutil/tests/test_osx.py -> build/lib.linux-x86_64-3.5/psutil/tests
    copying psutil/tests/test_memory_leaks.py -> build/lib.linux-x86_64-3.5/psutil/tests
    copying psutil/tests/test_sunos.py -> build/lib.linux-x86_64-3.5/psutil/tests
    copying psutil/tests/test_posix.py -> build/lib.linux-x86_64-3.5/psutil/tests
    copying psutil/tests/test_unicode.py -> build/lib.linux-x86_64-3.5/psutil/tests
    copying psutil/tests/test_contracts.py -> build/lib.linux-x86_64-3.5/psutil/tests
    copying psutil/tests/test_misc.py -> build/lib.linux-x86_64-3.5/psutil/tests
    copying psutil/tests/__init__.py -> build/lib.linux-x86_64-3.5/psutil/tests
    copying psutil/tests/__main__.py -> build/lib.linux-x86_64-3.5/psutil/tests
    copying psutil/tests/test_system.py -> build/lib.linux-x86_64-3.5/psutil/tests
    copying psutil/tests/test_windows.py -> build/lib.linux-x86_64-3.5/psutil/tests
    copying psutil/tests/test_process.py -> build/lib.linux-x86_64-3.5/psutil/tests
    copying psutil/tests/test_linux.py -> build/lib.linux-x86_64-3.5/psutil/tests
    copying psutil/tests/test_aix.py -> build/lib.linux-x86_64-3.5/psutil/tests
    running build_ext
    building 'psutil._psutil_linux' extension
    creating build/temp.linux-x86_64-3.5
    creating build/temp.linux-x86_64-3.5/psutil
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DPSUTIL_POSIX=1 -DPSUTIL_VERSION=540 -DPSUTIL_LINUX=1 -I/home/work/osroom/include -I/usr/include/python3.5m -c psutil/_psutil_common.c -o build/temp.linux-x86_64-3.5/psutil/_psutil_common.o
    psutil/_psutil_common.c:9:20: fatal error: Python.h: No such file or directory
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command "/home/work/osroom/bin/python3 -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-vroqxhun/psutil/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-878tn4xb/install-record.txt --single-version-externally-managed --compile --install-headers /home/work/osroom/include/site/python3.5/psutil" failed with error code 1 in /tmp/pip-install-vroqxhun/psutil/

**Comment by Elegant-Smile** [comment]
是否可以将此应用开发成docker版本？

**Comment by HiWoo** [comment]
@Elegant-Smile 一步一步来，最近比较忙

**Comment by Zhiing** [comment]
apt install python3-dev
