### ISSUE TITLE
没登录时，点击demo.osroom.com的文章，出现404；登录后，点击文章正常。

### ISSUE THREAD

**Issue by ilvxna** [osroom/osroom#17]

**Comment by HiWoo** [comment]
我发现了，登录不登录都部分文章都会404.
是前端安全没做好，遭受前端XSS攻击了，正在修复漏洞...

**Comment by HiWoo** [comment]
@ilvxna 我发现了，登录不登录都部分文章都会404.
是前端安全没做好，遭受前端XSS攻击了，正在修复漏洞...

**Comment by HiWoo** [comment]
@ilvxna 攻击者在评论里写js代码，而前端使用了vueJS的v-html来渲染评论内容，然后文章页面就执行了代码，导致404. 所以VUEJS的v-html不保证渲染安全。然后后端对文章发布和评论内容没有做很严格的安全过滤。

**Comment by HiWoo** [comment]
@ilvxna 
是XSS攻击，登录不登录，在部分文章都会404.
攻击者在评论里写js代码，而前端使用了vueJS的v-html来渲染评论内容，然后进入文章页面加载评论后，浏览器就执行了代码，加载攻击者的404图片，导致404. 
所以
1.VUEJS的v-html不保证渲染安全。
2.后端对文章发布和评论内容没有做很严格的过滤，因为后端对某些情况的XSS攻击过滤有效，但会引入其他不确定性和乱码问题

**Comment by HiWoo** [comment]
因为用户输入内容以后如何使用具有不确定性，后端不能对内容过意更改(编码)

**Comment by ilvxna** [comment]
所以这个安全问题，如何避免呢。刚刚demo.osroom.com也打不开了

**Comment by HiWoo** [comment]
@ilvxna 我昨晚吧網站暂时停了，现在启动了。
看了相关的资料，现在并没有绝对的避免方式，可以如下一些操作：
1. 在前端，能不插入渲染"**不可信任html**“就尽量不要插入渲染。
2. 前端html，js对不可信任的内容数据转义（对可以预见的那些转义，就像防止SQL注入一样）
3. 白名单、黑名单技术。。。
等
即使你用了以上全部，也不可完全避免，而且会耗费很大精力。

我现在在前端只是把OSR的主题原来通过v-html渲染评论，现在改成了直接显示字符串。
然后，在后端加了个过滤设置，管理员自己随时动态设置要过滤的提交内容。不过这个会就造成不确定性，比如：我设置过滤掉"insertHTML" , 可是用户在写一个JS教程，里面有"insertHTML“， 你却把它过滤了。

**Comment by ilvxna** [comment]
谢谢大大的回复。现在评论功能还未开放对吧？
