### ISSUE TITLE
如何添加权限，只有一定等级用户例如管理员才能发帖，其他人只能评论

### ISSUE THREAD

**Issue by ilvxna** [osroom/osroom#23]

**Comment by HiWoo** [comment]
@ilvxna 
[具体请查看文章 https://demo.osroom.com/post?id=5d1def71cd7c1f341eb1f250](https://demo.osroom.com/post?id=5d1def71cd7c1f341eb1f250)

### 文章发布权限修改
**1. API权限：/api/user/post**
修改 POST, PATCH, PUT, DELETE的权限
比如：修改为只允许STAFF(只允许工作人员和管理员，ROOT)
            修改为只允许ADMIN(只允许管理员和ROOT)

如果只修改api权限，则其他用户可以进入文章发布页面，但是无法提交内容

**1.发布页面的权限：osr-theme-w 主题的文章发布页面路由是 /content/writer**
如何权限管理里面没有/content/writer路由，则添加一个
然后在修改它的权限

### 评论功能权限
**方式1：去管理端>站点配置>comment里关闭评论功能**

https://<your domain>/osr-admin/setting/config-edit?project=comment

这种方式是全关闭评论功能

**方式2: 修改评论api权限(默认全部人能评论)**

API: /api/comment

修改 POST, PUT, PATCH, DELETE的权限

比如：修改为只允许STAFF(只允许工作人员和管理员，ROOT)

            修改为只允许ADMIN(只允许管理员和ROOT)

**Comment by ilvxna** [comment]
好的，学习了，谢谢大大。
