### ISSUE TITLE
最后一步了,输入http://127.0.0.1:5000/ 浏览器为什么打不开

### ISSUE THREAD

**Issue by huixiangdou** [osroom/osroom#29]
* Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)

**Comment by HiWoo** [comment]
如果你是在Linux虚拟机外部浏览器访问，需要使用局域网分布给虚拟机的IP范文， 而且web启动的时候指定--host 0.0.0.0

**Comment by huixiangdou** [comment]
谢谢您,这个问题已解决.
在最后一步的时候没有按CTRL + C退出.
按CTRL + C退出后,完美运行.
