### ISSUE TITLE
建议用mongoengine做下orm

### ISSUE THREAD

**Issue by yahuishuo** [osroom/osroom#3]
没有model对2次开发，不太友好

**Comment by HiWoo** [comment]
@yahuishuo 感谢你的建议！之前有考虑过使用这个库，可是很不喜欢那种方式，而且觉得好多坑。之后版本再考虑下它，也或者自己针对二次开发友好/耦合性问题优化。

**Comment by inchonline** [comment]
期待有orm版本出来

**Comment by HiWoo** [comment]
@inchonline 我不知为什么,很讨厌orm,有种它会把我捆绑了的感觉
