### ISSUE TITLE
新建栏目后，发布的地方还是没有下拉栏目列表

### ISSUE THREAD

**Issue by chenspnjupt** [osroom/osroom#30]
![image](https://user-images.githubusercontent.com/8540045/71319073-fd9f5b00-24d3-11ea-8778-4ab12765c9b7.png)
返回后，下拉列表中没有刚新建的栏目
![image](https://user-images.githubusercontent.com/8540045/71319079-10199480-24d4-11ea-825c-2eae5bab3084.png)

**Comment by HiWoo** [comment]
我刚看了，猜测你是在管理端那里发布内容页面进入的吧？管理端那边的发布功能我没有多关注。刚看了的确有问题，之后修复。
目前可用解决方案： 你发布内容不要在管理端那里发布就没有问题。从网站开放页面那里进入

/content/category?type=post&ps=&peditor=&pid=

**Comment by chenspnjupt** [comment]
> 我刚看了，猜测你是在管理端那里发布内容页面进入的吧？管理端那边的发布功能我没有多关注。刚看了的确有问题，之后修复。
> 目前可用解决方案： 你发布内容不要在管理端那里发布就没有问题。从网站开放页面那里进入
> 
> /content/category?type=post&ps=&peditor=&pid=

好的，谢谢！
