### ISSUE TITLE
使用SecretToken获取AccessToken的过程是否安全

### ISSUE THREAD

**Issue by young-tim** [osroom/osroom#35]
验证接口请求的RestToken内容包括两种形式：
①SecretToken：像是最高权限的token，可以任意请求接口。原则上应该尽量少使用；
②AccessToken和CliendId：每个客户端可以根据SecretToken请求生成。推荐使用该方式；

但问题是，请求生成AccessToken的过程中，需要在请求头中放置SecretToken。这样就很容易SecretToken泄露了吧？F12查找请求就看到了。

**Comment by HiWoo** [comment]
这个是不能用在普通网页的。
普通的网页使用的是临时的crsf_token, 网页从服务端过来时会带上，每次不一样。
而SecretToken，AccessToken和CliendId 这写都是给一些服务器请求api或者其他安全性高，不能看源代码的客户端的使用的。就像twiter，google他们提供的开发者API的Secret key类似

**Comment by young-tim** [comment]
在前后端（Vue）完全分离的情况下，无法直接使用flask的模板函数生成csrf_token。
是否有推荐方案？

目前我在before_request中，将csrf_token赋值(cookie)给浏览器，浏览器获得cookie中的csrf_token后，放置在请求头中请求接口。
但浏览器首次请求时，必然会报一次缺少X-CSRFToken的错误。因为首次请求时，cookie中仍未生成csrf_token。
我觉得这个操作方式还有更好的实现。

能否添加您微信/QQ私聊？

**Comment by HiWoo** [comment]
如果你的前端网页有web服务的话
可以在网页所在的服务器使用SecretToken验证，请求获取AccessToken，CliendId的api，获取到临时的验证Token(AccessToken，CliendId).
把AccessToken，CliendId放在响应里面跟着网页到浏览器。
然后网页请求api的时使用AccessToken，CliendId.
