### ISSUE TITLE
请问如果富文本中没有图片，在哪里配置让它默认显示文章背景图呢？

### ISSUE THREAD

**Issue by luoyudong593** [osroom/osroom#37]
![image](https://user-images.githubusercontent.com/54063226/78232533-f8a46b80-7506-11ea-93e8-be4facec95d2.png)

**Comment by luoyudong593** [comment]
在此处设置之后怎么没有效果呢
![image](https://user-images.githubusercontent.com/54063226/78269390-19d37f00-753c-11ea-8c12-be6d01ad5363.png)

**Comment by HiWoo** [comment]
（不知道为何我看不到你发的图片。可能网络问题）
根据的你问题：
在v2.0-v2.2版本是在
/osr-admin/setting/config-edit?project=theme_global_conf
中设置。
具体设置如下图片.(FREE中添加一个元素,key为post_cover_url, value为图片url)
![image](https://user-images.githubusercontent.com/14039952/78278356-7e94d680-7548-11ea-8ec6-b5214eff9404.png)

**Comment by HiWoo** [comment]
v3应该会优化这个设置

**Comment by luoyudong593** [comment]
好的，谢谢回复
