### ISSUE TITLE
网站部署使用几天后，无法正常使用，登录mongodb数据库发现所有的表都没了，请问是什么原因造成的呢？

### ISSUE THREAD

**Issue by luoyudong593** [osroom/osroom#38]
<h2>环境：
      按照教程中的操作步骤进行部署的，使用的环境基本一致</h2>

<h3>1.进入首页大面积空白，如下图：</h3> 

![image](https://user-images.githubusercontent.com/54063226/78350575-0249d400-75d8-11ea-9210-81775abf0e2a.png)

<h3>2.使用账号密码无法登录，如下图：</h3>

![image](https://user-images.githubusercontent.com/54063226/78351196-01657200-75d9-11ea-970a-10bbbabca574.png)

<h3>3.查看数据库，如下图：</h3>

![image](https://user-images.githubusercontent.com/54063226/78351080-d2e79700-75d8-11ea-9a52-42239ddb684f.png)

**Comment by HiWoo** [comment]
代码了没有任何mongo的drop操作，检查下是否进错了数据库？还有mongodb端口最好不要对外网开放

**Comment by HiWoo** [comment]
代码里没有任何mongo的drop操作，所以应该不会删coll。你检查下是否进错了数据库？还有mongodb端口最好不要对外网开放

**Comment by luoyudong593** [comment]
> 代码里没有任何mongo的drop操作，所以应该不会删coll。你检查下是否进错了数据库？还有mongodb端口最好不要对外网开放

好的，谢谢，原来是数据库被黑了
