### ISSUE TITLE
3.0 更新啥

### ISSUE THREAD

**Issue by justime** [osroom/osroom#40]
3.0 会更新啥内容

**Comment by HiWoo** [comment]
更新一些后端代码逻辑，部分功能，修复一些bug。主题和Admin的UI也会做一些调整

**Comment by justime** [comment]
加油，大概啥时候更新呢？期待

**Comment by justime** [comment]
java 语言的 solo  和  mblog 两个开源项目做得还不错，UI和功能可以借鉴借鉴
