### ISSUE TITLE
无法更改更改用户角色

### ISSUE THREAD

**Issue by luoyudong593** [osroom/osroom#41]
使用的版本为2.2
![image](https://user-images.githubusercontent.com/54063226/80856702-aaf25e80-8c7e-11ea-8968-bd0fc5ed1b4b.png)
![image](https://user-images.githubusercontent.com/54063226/80856726-df661a80-8c7e-11ea-98d0-3b2c2c9bf9c4.png)

请问一下这块的功能是不是还没有实现呢？

**Comment by luoyudong593** [comment]
现在用户权限通过数据库修改为超级管理员后，为什么还是不能进入管理后台(首页中没有这个导航条)呢![Uploading image.png…]()

**Comment by luoyudong593** [comment]
![image](https://user-images.githubusercontent.com/54063226/80857928-62d83980-8c88-11ea-8744-5a52efcdb727.png)
![image](https://user-images.githubusercontent.com/54063226/80857935-6d92ce80-8c88-11ea-9f7b-f00f82a9422b.png)

**Comment by HiWoo** [comment]
数据库直接修改？因为redis缓存没有过期
