### ISSUE TITLE
能够提供下安装部署说明吗？谢谢~

### ISSUE THREAD

**Issue by LianWilliam** [osroom/osroom#8]
能够提供下安装部署说明，谢谢~

**Comment by HiWoo** [comment]
@LianWilliam 之前网站有，现在关掉了，我看下在什么地方弄份到网上

**Comment by HiWoo** [comment]
@LianWilliam 文档地址 [https://osroom.github.io/osroom-doc/](https://osroom.github.io/osroom-doc/)
